name: Fix Texture Pack Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move to correct structure
        run: |
          mkdir -p PACK/assets/minecraft
          # 既存の間違った階層を移動
          if [ -d "PACK/minecraft/assets" ]; then
            mv PACK/minecraft/assets/* PACK/assets/minecraft/
            rm -rf PACK/minecraft
          fi
          # pack.mcmeta はそのまま残っているならOK、無ければ移動
          if [ -f "PACK/pack.mcmeta" ]; then
            echo "pack.mcmeta exists"
          fi

      - name: ZIP the fixed pack
        run: |
          cd PACK
          zip -r ../MemePack-fixed.zip .
          cd ..

      - name: Upload fixed ZIP
        uses: actions/upload-artifact@v3
        with:
          name: MemePack-fixed
          path: MemePack-fixed.zip
